# Generated by Django 4.1 on 2022-09-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
